import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nathan Chesmar Porfolio</title>
        <meta name="description" content="Generated by Nate Chesmar" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Velo on Exit</h1>
      <h3>Lineup and Batted Ball Analysis</h3>
    </div>
  )
}
