const mongoose = require('mongoose')

const apiHitterSeasonSchema = new mongoose.Schema(
  {
    sport_id: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 15,
    },
    league_short: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 15,
    },
    hr: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    team_id: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 15,
    },
    season: {
      type: String,
      required: false,
      minlength: 0,
      maximum: 6,
    },
    ab: {
      type: Number,
      required: false,
      minlength: 0,
      maxlength: 800,
    },
    hldr: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    league: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 15,
    },
    sport_code: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 15,
    },
    ao: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    slg1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 2000,
    },
    team_full: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 50,
    },
    ops1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 5000,
    },
    team_abbrev: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 10,
    },
    hbp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    rbi: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 220,
    },
    go_ao1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000000,
    },
    hfly: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    lob: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 600,
    },
    xbh: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    end_date: {
      type: String,
      required: false,
    },
    bb: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    np: {
      type: Number,
      required: false,
      min: 0,
      maximum: 5000,
    },
    hgnd: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    roe: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    sb: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    player_id: {
      type: String,
      required: true,
      minlength: 0,
      maxlength: 10,
    },
    avg1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    sf: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sac: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    wo: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    team_short: {
      type: String,
      minlength: 0,
      maxlength: 30,
      required: false,
    },
    hpop: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    so: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    gidp_opp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    gidp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 80,
    },
    ppa100: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000000,
    },
    d: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 400,
    },
    tpa: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 800,
    },
    league_full: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 35,
    },
    g: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    h: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    ibb: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    go: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    team_seq: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 10,
    },
    tb: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    cs: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 120,
    },
    r: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 220,
    },
    t: {
      type: String,
      minlength: 0,
      maxlength: 5,
    },
    babip1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    obp1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    sport: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 10,
    },
    league_id: {
      type: String,
      required: false,
      minlength: 0,
      maxlength: 10,
    },
  },
  { timestamps: true }
)

// create and export the model
module.exports = mongoose.model('ApiHitterSeason', apiHitterSeasonSchema)
