const mongoose = require('mongoose')

const playerPercentileSchema = new mongoose.Schema(
  {
    hr: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hrPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    season: {
      type: String,
      required: false,
      minlength: 0,
      maximum: 6,
    },
    ab: {
      type: Number,
      required: false,
      minlength: 0,
      maxlength: 800,
    },
    abPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hldr: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    hldrPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    ao: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    aoPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    slg1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 4000,
    },
    slg1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    ops1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 5000,
    },
    ops1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hbp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    hbpPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    rbi: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 220,
    },
    rbiPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    go_ao1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000000,
    },
    go_ao1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hfly: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    hflyPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    lob: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 600,
    },
    lobPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    xbh: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    xbhPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    bb: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    bbPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    np: {
      type: Number,
      required: false,
      min: 0,
      maximum: 5000,
    },
    npPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hgnd: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    hgndPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    roe: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    roePerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sb: {
      type: Number,
      required: false,
      min: 0,
      maximum: 300,
    },
    sbPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    player_id: {
      type: String,
      required: true,
      minlength: 0,
      maxlength: 10,
    },
    avg1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    avg1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sf: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sfPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sac: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    sacPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    wo: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    woPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hpop: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    hpopPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    so: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    soPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    gidp_opp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    gidp_oppPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    gidp: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 80,
    },
    gidpPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    ppa100: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000000,
    },
    ppa100Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    d: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 400,
    },
    dPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    tpa: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 800,
    },
    tpaPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    g: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 200,
    },
    gPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    h: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    hPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    ibb: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    ibbPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    go: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 300,
    },
    goPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    tb: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 500,
    },
    tbPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    cs: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 120,
    },
    csPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    r: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 220,
    },
    rPerc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    babip1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    babip1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
    obp1000: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 1000,
    },
    obp1000Perc: {
      type: Number,
      required: false,
      minimum: 0,
      maximum: 100,
    },
  },
  { timestamps: true }
)

// create and export the model
module.exports = mongoose.model('PlayerPercentile', playerPercentileSchema)
